// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvu7MYeztgJtNJ5gtxmKDB6So-Gkc13HA',
    appId: '1:135770064569:web:87f3be6f7a1592c378fd68',
    messagingSenderId: '135770064569',
    projectId: 'health-tracker-app-c18c8',
    authDomain: 'health-tracker-app-c18c8.firebaseapp.com',
    storageBucket: 'health-tracker-app-c18c8.appspot.com',
    measurementId: 'G-5ZM6YRL33C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe4u9j04-xsWfeUQ5TVrr0vbHsTibC97E',
    appId: '1:135770064569:android:080b3d1fbe3d35f878fd68',
    messagingSenderId: '135770064569',
    projectId: 'health-tracker-app-c18c8',
    storageBucket: 'health-tracker-app-c18c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzR-udKRSTcoOri6u7Lk4bZ4tuWlYY7Oo',
    appId: '1:135770064569:ios:d12243b54d367fb078fd68',
    messagingSenderId: '135770064569',
    projectId: 'health-tracker-app-c18c8',
    storageBucket: 'health-tracker-app-c18c8.appspot.com',
    iosBundleId: 'com.example.healthTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzR-udKRSTcoOri6u7Lk4bZ4tuWlYY7Oo',
    appId: '1:135770064569:ios:d12243b54d367fb078fd68',
    messagingSenderId: '135770064569',
    projectId: 'health-tracker-app-c18c8',
    storageBucket: 'health-tracker-app-c18c8.appspot.com',
    iosBundleId: 'com.example.healthTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvu7MYeztgJtNJ5gtxmKDB6So-Gkc13HA',
    appId: '1:135770064569:web:75042be766f70dcb78fd68',
    messagingSenderId: '135770064569',
    projectId: 'health-tracker-app-c18c8',
    authDomain: 'health-tracker-app-c18c8.firebaseapp.com',
    storageBucket: 'health-tracker-app-c18c8.appspot.com',
    measurementId: 'G-RLFV4464H2',
  );
}
